const TF_TITLES = {
    'TF_COURSE_TITLE_SIMPLE': '简单',
    'TF_COURSE_TITLE_NORMAL': '中等',
    'TF_COURSE_TITLE_HARD': '困难',
    'TF_COURSE_TITLE_EXPERT': '大师',
    'TF_COURSE_TITLE_HERO': '英雄',
    'TF_COURSE_TITLE_PRACTICE': '从入门到放弃',
}

module.exports = {
    TF_TITLES,
    TF_COURSES: [
        TF_TITLES.TF_COURSE_TITLE_PRACTICE,
        TF_TITLES.TF_COURSE_TITLE_SIMPLE,
        TF_TITLES.TF_COURSE_TITLE_NORMAL,
        TF_TITLES.TF_COURSE_TITLE_HARD,
        TF_TITLES.TF_COURSE_TITLE_EXPERT,
        TF_TITLES.TF_COURSE_TITLE_HERO
    ]
}